@extends('layouts.app', ['title' => $action->title.' - 継続実行'])
@section('content')
<section class="stack" style="max-width:1000px;margin:auto">
    @if(session('status')) <div class="panel">{{ session('status') }}</div> @endif
    <div class="page-header"><div><div class="meta">ACTION / EXECUTION</div><h1>{{ $action->title }}</h1><p>{{ $project->name }}</p></div><a href="{{ route('project-execution.show', $project) }}">Projectへ戻る</a></div>
    @if($canConfigure && $action->runSetting)
    <div class="actions"><form method="POST" action="{{ route('action-executions.'.($action->runSetting->control_status === 'paused' ? 'resume' : 'pause'), [$project, $action]) }}">@csrf<input type="hidden" name="project_version" value="{{ $project->plan_version }}"><input name="reason" required placeholder="{{ $action->runSetting->control_status === 'paused' ? '再開理由' : '停止理由' }}"><button class="secondary">{{ $action->runSetting->control_status === 'paused' ? '継続予定を再開' : '継続予定を停止' }}</button></form></div>
    @endif
    @if($canConfigure)
    <form class="panel stack" method="POST" action="{{ route('action-executions.configure', [$project, $action]) }}">@csrf
        <input type="hidden" name="project_version" value="{{ $project->plan_version }}"><h2>実施予定を設定</h2>
        <div class="grid"><label>種類<select name="run_type"><option value="continuous">継続</option><option value="one_time">予定付き単発</option></select></label><label>カテゴリ<select name="category"><option value="task">業務</option><option value="communication">発信</option><option value="check">確認</option><option value="follow_up">フォロー</option><option value="other">その他</option></select></label><label>頻度<select name="frequency"><option value="daily">毎日</option><option value="weekday">平日</option><option value="weekly">毎週</option><option value="monthly">毎月</option><option value="custom">カスタム</option></select></label><label>間隔<input type="number" name="interval" value="1" min="1"></label></div>
        <div class="grid"><label>実施ルール<select name="execution_rule"><option value="on_date">指定日に実施</option><option value="by_date">指定日までに実施</option><option value="within_window">期間内に実施</option></select></label><label>開始日<input type="date" name="starts_on" required value="{{ now()->toDateString() }}"></label><label>終了日<input type="date" name="ends_on"></label><label>正規予定回数<input type="number" name="count_limit" min="1"></label></div>
        <div class="grid"><label>毎月の日<input type="number" name="month_day" min="1" max="31"></label><label><input type="checkbox" name="month_end" value="1"> 月末</label><label>期間開始までの日数<input type="number" name="window_days_before" value="0" min="0"></label></div>
        <h3>発信情報（外部送信はしません）</h3>
        @if(session('ai_draft_suggestion'))<div class="notice stack"><strong>AI文案（まだ保存されていません）</strong><textarea id="ai-draft-suggestion" rows="5" readonly>{{ session('ai_draft_suggestion') }}</textarea><button type="button" class="secondary" onclick="document.querySelector('[name=communication_draft]').value=document.getElementById('ai-draft-suggestion').value">この文案を採用して編集する</button></div>@endif<label>誰に<input name="communication_target" maxlength="500" value="{{ old('communication_target', $action->runSetting?->communication_target) }}"></label><label>予定時刻<input type="time" name="communication_time" value="{{ old('communication_time', $action->runSetting?->communication_time) }}"></label><label>文案<textarea name="communication_draft" rows="5">{{ old('communication_draft', $action->runSetting?->communication_draft) }}</textarea></label><p class="meta">ここでの「予約保存」は予定と文案の保存です。外部サービスへの送信予約ではありません。</p><label>変更理由<input name="reason" maxlength="1000"></label><button type="submit">予定を保存</button>
    </form>
    <form class="panel stack" method="POST" action="{{ route('action-executions.draft', [$project, $action]) }}">@csrf<h3>AIで文案を作る</h3><p class="meta">本人が実行した場合だけ、発信先の説明・Action title・Done Condition・下記指示をAIへ送ります。保存や外部送信はしません。</p><label>発信先の説明<input name="communication_target" required maxlength="500" value="{{ old('communication_target', $action->runSetting?->communication_target) }}"></label><label>文案指示<textarea name="draft_instruction" required maxlength="2000">{{ old('draft_instruction') }}</textarea></label><button type="submit">AIで文案を作る</button></form>
    @endif
    <div class="panel stack"><h2>実施履歴</h2>@forelse($action->executions as $execution)<article class="card"><div class="actions" style="justify-content:space-between"><strong>{{ $execution->scheduled_date->format('Y.m.d') }}</strong><span class="badge">{{ $execution->status }} / {{ $execution->origin }}</span></div>@if($execution->memo)<p>{{ $execution->memo }}</p>@endif
        @if($execution->status === 'planned')<div class="actions"><form method="POST" action="{{ route('action-executions.complete', $execution) }}">@csrf<input type="hidden" name="operation_id" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button>実施した</button></form><form method="POST" action="{{ route('action-executions.skip', $execution) }}">@csrf<input type="hidden" name="operation_id" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><input name="reason" required placeholder="見送り理由"><button class="secondary">見送る</button></form></div>@elseif($execution->status === 'missed')<form method="POST" action="{{ route('action-executions.retry', $execution) }}">@csrf<input type="hidden" name="operation_id" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button>今日、再実施する</button></form>@endif</article>@empty<p class="meta">実施予定はまだありません。</p>@endforelse</div>
</section>
@endsection
