<?php
declare(strict_types=1);
use App\Models\Capture;use App\Models\Organization;use App\Models\OrganizationUser;use App\Models\ProductAccountEligibility;use App\Models\User;use App\Models\Workspace;use App\Services\Capture\CaptureWriter;use App\Services\ProjectExecution\ProjectExecutionWriter;use Illuminate\Contracts\Console\Kernel;use Illuminate\Support\Facades\Hash;
require dirname(__DIR__,2).'/vendor/autoload.php';
$app=require dirname(__DIR__,2).'/bootstrap/app.php';$app->make(Kernel::class)->bootstrap();
if(config('database.default')!=='mysql'||config('database.connections.mysql.host')!=='127.0.0.1'||(int)config('database.connections.mysql.port')!==13319||config('database.connections.mysql.database')!=='co_capture_tqc')throw new RuntimeException('Capture MariaDB guard rejected target.');
$mode=$argv[1]??'';
if($mode==='seed'){$owner=User::create(['name'=>'Capture Owner','email'=>'capture-owner@example.test','password'=>Hash::make('x'),'is_active'=>true]);$recipient=User::create(['name'=>'Capture Recipient','email'=>'capture-recipient@example.test','password'=>Hash::make('x'),'is_active'=>true]);$org=Organization::create(['name'=>'Capture Isolated','slug'=>'capture-isolated']);$ws=Workspace::create(['organization_id'=>$org->id,'owner_user_id'=>$owner->id,'name'=>'Capture','slug'=>'capture','status'=>Workspace::STATUS_ACTIVE]);foreach([[$owner,'owner'],[$recipient,'member']]as[$user,$role]){OrganizationUser::create(['organization_id'=>$org->id,'user_id'=>$user->id,'role'=>$role,'organization_role'=>$role,'membership_status'=>OrganizationUser::STATUS_ACTIVE,'access_epoch'=>1,'lifecycle_version'=>1,'permissions'=>[],'joined_at'=>now()]);$ws->users()->attach($user->id,['role'=>$role,'joined_at'=>now()]);ProductAccountEligibility::create(['user_id'=>$user->id,'mode'=>ProductAccountEligibility::MODE_SINGLE,'product_organization_id'=>$org->id,'classification_version'=>'capture-mariadb','classified_at'=>now(),'evidence_ref'=>'capture-mariadb']);}$pw=app(ProjectExecutionWriter::class);$project=$pw->createProject($owner,$ws,['name'=>'Capture Promotion','purpose'=>'Concurrency','expected_outcome'=>'Exactly once']);$pw->addMember($owner,$project->fresh(),$recipient,$ws,['member'],$project->fresh()->plan_version);echo json_encode(['organization'=>$org->id,'project'=>$project->id]);exit;}
if($mode==='create'){$barrier=$argv[2]??'';while(!is_file($barrier))usleep(20000);$owner=User::where('email','capture-owner@example.test')->firstOrFail();$recipient=User::where('email','capture-recipient@example.test')->firstOrFail();$org=Organization::where('slug','capture-isolated')->firstOrFail();$capture=app(CaptureWriter::class)->create($owner,$org,['operation_id'=>'11111111-1111-4111-8111-111111111111','type'=>'request','body'=>'Concurrent capture','recipient_user_id'=>$recipient->id,'notification_timing'=>'now']);echo json_encode(['capture_id'=>$capture->id]);exit;}
if($mode==='promote'){$barrier=$argv[2]??'';while(!is_file($barrier))usleep(20000);$owner=User::where('email','capture-owner@example.test')->firstOrFail();$capture=Capture::where('create_operation_id','11111111-1111-4111-8111-111111111111')->firstOrFail();$project=$capture->organization->workspaces()->firstOrFail()->projects()->firstOrFail();$task=app(CaptureWriter::class)->promote($owner,$capture,$project,['operation_id'=>'22222222-2222-4222-8222-222222222222','title'=>'Concurrent action','done_condition'=>'One action','confirm_project_visibility'=>true],$capture->version,$project->plan_version);echo json_encode(['task_id'=>$task->id]);exit;}
throw new RuntimeException('Unknown mode.');
