<?php
declare(strict_types=1);
use App\Models\Organization; use App\Models\OrganizationUser; use App\Models\User; use App\Models\Workspace; use App\Models\WorkspaceAiSetting;
use App\Services\ActionExecution\ActionExecutionWriter; use App\Services\ProjectExecution\ProjectExecutionWriter;
use Illuminate\Contracts\Console\Kernel; use Illuminate\Support\Facades\Artisan; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Str;
require dirname(__DIR__, 2).'/vendor/autoload.php';
$path=$argv[1]??''; $temp=realpath(sys_get_temp_dir()); $dir=$path===''?false:realpath(dirname($path)); $name=basename($path);
if($temp===false||$dir!==$temp||!str_starts_with($name,'company-os-scope9-browser-')||!str_ends_with($name,'.sqlite')){fwrite(STDERR,"Refusing non-Scope 9 temp database.\n");exit(64);} if(is_file($path))unlink($path);touch($path);
$app=require dirname(__DIR__,2).'/bootstrap/app.php';$app->make(Kernel::class)->bootstrap();config(['app.env'=>'testing','app.url'=>env('APP_URL','http://127.0.0.1:8766'),'database.default'=>'sqlite','database.connections.sqlite.database'=>$path,'product_ux.organization_admission_enabled'=>false]);DB::purge('sqlite');Artisan::call('migrate:fresh',['--database'=>'sqlite','--force'=>true]);
$org=Organization::create(['name'=>'Scope 9 Browser Company','slug'=>'scope9-browser-'.strtolower((string)Str::ulid())]);$owner=User::create(['name'=>'Scope 9 Owner','email'=>'scope9-owner@example.test','email_verified_at'=>now(),'password'=>Hash::make('not-used'),'is_active'=>true]);OrganizationUser::create(['organization_id'=>$org->id,'user_id'=>$owner->id,'role'=>'owner','organization_role'=>'owner','membership_status'=>'active','access_epoch'=>1,'lifecycle_version'=>1,'permissions'=>[],'joined_at'=>now()]);
$workspace=Workspace::create(['organization_id'=>$org->id,'owner_user_id'=>$owner->id,'name'=>'Execution Workspace','slug'=>'scope9-execution','type'=>Workspace::TYPE_SHARED,'status'=>Workspace::STATUS_ACTIVE]);$workspace->users()->attach($owner->id,['role'=>'owner','joined_at'=>now()]);WorkspaceAiSetting::create(['workspace_id'=>$workspace->id,'enabled'=>true,'provider'=>'browser-evidence','allowed_data_categories'=>['project_metadata','tasks'],'terms_version'=>WorkspaceAiSetting::TERMS_VERSION,'enabled_by'=>$owner->id,'enabled_at'=>now()]);
$s8=app(ProjectExecutionWriter::class);$project=$s8->createProject($owner,$workspace,['name'=>'Continuous Customer Care','purpose'=>'Maintain customer trust','expected_outcome'=>'Every follow-up is visible']);$action=$s8->createAction($owner,$project->fresh(),['title'=>'Customer follow-up','done_condition'=>'Contact is recorded','assigned_to'=>$owner->id],$project->fresh()->plan_version);
app(ActionExecutionWriter::class)->configure($owner,$action,['run_type'=>'continuous','category'=>'communication','frequency'=>'daily','interval'=>1,'execution_rule'=>'on_date','window_days_before'=>0,'starts_on'=>now()->toDateString(),'count_limit'=>2,'communication_target'=>'Customer contact','communication_draft'=>'Thank you for your time.','communication_time'=>'10:00'],$project->fresh()->plan_version);
echo json_encode(['database'=>$path,'project_id'=>$project->id,'action_id'=>$action->id],JSON_UNESCAPED_SLASHES).PHP_EOL;
