<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('captures',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->foreignId('organization_id')->constrained()->restrictOnDelete();$t->foreignId('creator_user_id')->constrained('users')->restrictOnDelete();$t->foreignId('recipient_user_id')->constrained('users')->restrictOnDelete();$t->string('type',24);$t->text('body');$t->string('notification_timing',24)->default('now');$t->timestamp('notify_at_utc')->nullable();$t->string('status',24)->default('open');$t->unsignedInteger('version')->default(1);$t->uuid('create_operation_id')->unique();$t->char('create_payload_hash',64);$t->unsignedBigInteger('creator_access_epoch');$t->unsignedBigInteger('recipient_access_epoch');$t->unsignedBigInteger('creator_credential_generation');$t->unsignedBigInteger('recipient_credential_generation');$t->timestamp('acknowledged_at_utc')->nullable();$t->foreignId('acknowledged_by_user_id')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('closed_at_utc')->nullable();$t->foreignId('closed_by_user_id')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('cancelled_at_utc')->nullable();$t->foreignId('cancelled_by_user_id')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('converted_at_utc')->nullable();$t->foreignId('converted_by_user_id')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();$t->index(['organization_id','recipient_user_id','status']);$t->index(['organization_id','creator_user_id','status']);});
  Schema::create('capture_events',function(Blueprint $t):void{$t->id();$t->foreignId('capture_id')->constrained()->restrictOnDelete();$t->foreignId('actor_user_id')->constrained('users')->restrictOnDelete();$t->string('event_type',32);$t->uuid('operation_id')->unique();$t->unsignedInteger('capture_version');$t->json('metadata')->nullable();$t->timestamp('occurred_at_utc');$t->timestamps();$t->unique(['capture_id','capture_version']);});
  Schema::create('capture_action_relations',function(Blueprint $t):void{$t->id();$t->foreignId('capture_id')->unique()->constrained()->restrictOnDelete();$t->foreignId('project_id')->constrained()->restrictOnDelete();$t->foreignId('task_id')->unique()->constrained('tasks')->restrictOnDelete();$t->foreignId('promoted_by_user_id')->constrained('users')->restrictOnDelete();$t->uuid('operation_id')->unique();$t->timestamps();});
 }
 public function down(): void {Schema::dropIfExists('capture_action_relations');Schema::dropIfExists('capture_events');Schema::dropIfExists('captures');}
};
