@extends('layouts.app', ['title' => '見積書を作成 - '.$project->name])
@section('content')
@php $rows=collect(); foreach($project->roadmaps as $roadmap){$rows->push(['type'=>'roadmap','id'=>$roadmap->id,'title'=>$roadmap->title,'level'=>0]);foreach($roadmap->improvements as $improvement){$rows->push(['type'=>'improvement','id'=>$improvement->id,'title'=>$improvement->title,'level'=>1]);foreach($improvement->tasks as $task)$rows->push(['type'=>'task','id'=>$task->id,'title'=>$task->title,'level'=>2]);}} foreach($project->improvements->whereNull('roadmap_id') as $improvement){$rows->push(['type'=>'improvement','id'=>$improvement->id,'title'=>$improvement->title,'level'=>0]);foreach($improvement->tasks as $task)$rows->push(['type'=>'task','id'=>$task->id,'title'=>$task->title,'level'=>1]);} @endphp
<section class="stack">
    <div><div class="meta">{{ $project->client->name }} / {{ $project->name }}</div><h1>見積書を作成</h1><p>見積へ載せる項目を選び、数量と単価を入力します。保存後はProject側を変更しても見積内容は変わりません。</p></div>
    @if($errors->any())<div class="error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('projects.estimates.store',$project) }}" class="stack">@csrf
        <section class="card stack"><h2>基本情報</h2><div class="base-grid"><div class="field span-2"><label>件名 <span class="required-mark">必須</span></label><input name="title" value="{{ old('title',$project->name.' 御見積') }}" required></div><div class="field"><label>発行日</label><input type="date" name="issued_on" value="{{ old('issued_on',now()->toDateString()) }}" required></div><div class="field"><label>有効期限</label><input type="date" name="valid_until" value="{{ old('valid_until',now()->addMonth()->toDateString()) }}"></div></div></section>
        <section class="card stack"><div><h2>見積明細</h2><p class="meta">ロードマップ・取り組み・タスクのうち、必要な粒度だけ選択してください。</p></div><div class="estimate-items">
            @forelse($rows as $index=>$row)<div class="estimate-item level-{{ $row['level'] }}"><input type="hidden" name="items[{{ $index }}][selected]" value="0"><label class="select-item"><input type="checkbox" name="items[{{ $index }}][selected]" value="1" @checked(old("items.$index.selected"))><span class="type type-{{ $row['type'] }}">{{ ['roadmap'=>'ロードマップ','improvement'=>'取り組み','task'=>'タスク'][$row['type']] }}</span></label><input type="hidden" name="items[{{ $index }}][source_type]" value="{{ $row['type'] }}"><input type="hidden" name="items[{{ $index }}][source_id]" value="{{ $row['id'] }}"><div class="field description"><label>明細名</label><input name="items[{{ $index }}][description]" value="{{ old("items.$index.description",$row['title']) }}" required></div><div class="field small"><label>数量</label><input type="number" step="0.001" min="0.001" name="items[{{ $index }}][quantity]" value="{{ old("items.$index.quantity",1) }}" required></div><div class="field small"><label>単位</label><input name="items[{{ $index }}][unit]" value="{{ old("items.$index.unit",'式') }}" required></div><div class="field price"><label>単価（円）</label><input type="number" min="0" name="items[{{ $index }}][unit_price]" value="{{ old("items.$index.unit_price",0) }}" required></div><div class="field tax"><label>税率</label><select name="items[{{ $index }}][tax_rate]"><option value="10">10%</option><option value="8">8%</option><option value="0">0%</option></select></div></div>
            @empty<p>見積明細にできる項目がありません。先にロードマップ・取り組み・タスクを作成してください。</p>@endforelse
        </div></section>
        <section class="card stack"><div class="base-grid"><div class="field"><label>値引き（円）</label><input type="number" name="discount" min="0" value="{{ old('discount',0) }}"></div><div class="field span-2"><label>備考・支払条件</label><textarea name="notes" rows="4">{{ old('notes') }}</textarea></div></div></section>
        <div class="actions"><button type="submit">見積書を下書き保存</button><a class="button secondary" href="{{ route('projects.show',$project) }}">Projectへ戻る</a></div>
    </form>
</section>
<style>.base-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.span-2{grid-column:1/-1}.required-mark{padding:2px 6px;border-radius:999px;background:#fff0ed;color:#a84e3c;font-size:10px}.estimate-items{display:grid;gap:8px}.estimate-item{display:grid;grid-template-columns:135px minmax(220px,1fr) 85px 75px 120px 80px;gap:8px;align-items:end;padding:10px;border:1px solid var(--line);border-radius:8px;background:#fff}.estimate-item.level-1{margin-left:24px}.estimate-item.level-2{margin-left:48px}.select-item{display:flex;align-items:center;gap:7px;min-height:42px}.select-item input{width:auto}.type{font-size:11px;font-weight:800}.type-roadmap{color:#245ca6}.type-improvement{color:#23845c}.type-task{color:#b5523d}.estimate-item .field{margin:0}@media(max-width:900px){.estimate-item{grid-template-columns:1fr 1fr}.description{grid-column:1/-1}.estimate-item.level-1,.estimate-item.level-2{margin-left:0}.base-grid{grid-template-columns:1fr}.span-2{grid-column:auto}}</style>
@endsection
