@extends('layouts.app', ['title' => '見積書を編集'])
@section('content')
<section class="stack">
    <div><div class="meta">{{ $estimate->estimate_number }} / 第{{ $estimate->revision_no }}版</div><h1>見積書を編集</h1><p>下書きの内容を編集します。提出後は直接変更せず、改訂版を作成してください。</p></div>
    @if($errors->any())<div class="error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form id="estimate-edit-form" method="POST" action="{{ route('estimates.update', $estimate) }}" class="stack">@csrf @method('PUT')
        <section class="card edit-grid"><div class="field span"><label>件名</label><input name="title" value="{{ old('title', $estimate->title) }}" required></div><div class="field"><label>発行日</label><input type="date" name="issued_on" value="{{ old('issued_on', $estimate->issued_on->toDateString()) }}" required></div><div class="field"><label>有効期限</label><input type="date" name="valid_until" value="{{ old('valid_until', $estimate->valid_until?->toDateString()) }}"></div></section>
        <section class="card stack"><div class="row-head"><div><h2>明細・作業範囲</h2><p class="meta">金額に含めない説明項目は「作業範囲」にします。</p></div><button class="button secondary" id="add-estimate-line" type="button">項目を追加</button></div><div id="edit-lines" class="edit-lines">
            @foreach($estimate->items as $index => $item)
                <div class="edit-line"><input type="hidden" name="items[{{ $index }}][source_type]" value="{{ $item->source_type }}"><input type="hidden" name="items[{{ $index }}][source_id]" value="{{ $item->source_id }}"><input type="hidden" name="items[{{ $index }}][source_public_id]" value="{{ $item->source_public_id }}"><div class="field desc"><label>内容</label><input name="items[{{ $index }}][description]" value="{{ $item->description }}" required></div><div class="field"><label>数量</label><input type="number" step="0.001" min="0.001" name="items[{{ $index }}][quantity]" value="{{ (float)$item->quantity }}" required></div><div class="field"><label>単位</label><input name="items[{{ $index }}][unit]" value="{{ $item->unit }}" required></div><div class="field"><label>単価</label><input type="number" min="0" name="items[{{ $index }}][unit_price]" value="{{ $item->unit_price }}" required></div><div class="field"><label>税率</label><select name="items[{{ $index }}][tax_rate]"><option value="10" @selected((float)$item->tax_rate===10.0)>10%</option><option value="8" @selected((float)$item->tax_rate===8.0)>8%</option><option value="0" @selected((float)$item->tax_rate===0.0)>0%</option></select></div><label class="scope-check"><input type="hidden" name="items[{{ $index }}][is_scope_only]" value="0"><input type="checkbox" name="items[{{ $index }}][is_scope_only]" value="1" @checked($item->is_scope_only)>作業範囲</label><button class="remove-line" type="button">削除</button></div>
            @endforeach
        </div></section>
        <section class="card edit-grid"><div class="field"><label>値引き（円）</label><input type="number" name="discount" min="0" value="{{ old('discount', $estimate->discount) }}"></div><div class="field span"><label>備考・支払条件</label><textarea name="notes" rows="4">{{ old('notes', $estimate->notes) }}</textarea></div></section>
        <div class="actions"><button type="submit">変更を保存</button><a class="button secondary" href="{{ route('estimates.show', $estimate) }}">戻る</a></div>
    </form>
</section>
<template id="line-template"><div class="edit-line"><input type="hidden" data-name="source_type" value="manual"><div class="field desc"><label>内容</label><input data-name="description" required></div><div class="field"><label>数量</label><input type="number" step="0.001" min="0.001" data-name="quantity" value="1" required></div><div class="field"><label>単位</label><input data-name="unit" value="式" required></div><div class="field"><label>単価</label><input type="number" min="0" data-name="unit_price" value="0" required></div><div class="field"><label>税率</label><select data-name="tax_rate"><option value="10">10%</option><option value="8">8%</option><option value="0">0%</option></select></div><label class="scope-check"><input type="hidden" data-name="is_scope_only" value="0"><input type="checkbox" data-name="is_scope_only" value="1">作業範囲</label><button class="remove-line" type="button">削除</button></div></template>
<style>.edit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.span{grid-column:1/-1}.row-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.edit-lines{display:grid;gap:10px}.edit-line{display:grid;grid-template-columns:minmax(220px,1fr) 85px 75px 110px 80px 110px 60px;gap:8px;align-items:end;padding:10px;border:1px solid var(--line);border-radius:8px}.edit-line .field{margin:0}.scope-check{display:flex;gap:6px;align-items:center;min-height:42px}.scope-check input{width:auto}.remove-line{background:#fff;color:#a04435;border:1px solid #d8aaa1;padding:9px}@media(max-width:900px){.edit-line,.edit-grid{grid-template-columns:1fr 1fr}.edit-line .desc{grid-column:1/-1}.span{grid-column:1/-1}}</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const box=document.getElementById('edit-lines');const renumber=()=>{[...box.querySelectorAll('.edit-line')].forEach((row,i)=>row.querySelectorAll('[name],[data-name]').forEach(input=>{const key=input.dataset.name||input.name.match(/\[([^\]]+)\]$/)?.[1];if(key)input.name=`items[${i}][${key}]`}))};box.addEventListener('click',e=>{if(e.target.classList.contains('remove-line')){e.target.closest('.edit-line').remove();renumber()}});document.getElementById('add-estimate-line').addEventListener('click',()=>{box.append(document.getElementById('line-template').content.cloneNode(true));renumber()});renumber()});</script>
@endsection
