<article class="s8-action"><div class="s8-toolbar"><strong>{{ $action->title }}</strong><span class="s8-chip">{{ \App\Models\Task::executionStatuses()[$action->status] ?? $action->status }}</span></div><p>{{ $action->done_condition }}</p><div class="s8-meta"><span>担当 {{ $action->assignee?->name }}</span>@if($action->reviewer)<span>Reviewer {{ $action->reviewer->name }}</span>@endif</div>
@php($commands = $action->assigned_to === auth()->id() ? ['start'=>'開始','complete'=>'完了または確認依頼'] : ($action->reviewer_user_id === auth()->id() ? ['confirm'=>'確認','reject'=>'差戻し'] : ($project->owner_user_id === auth()->id() && $action->status === 'done' ? ['reopen'=>'再開'] : [])))
@foreach($commands as $command=>$label)<form method="POST" action="{{ route('project-execution.actions.transition', [$project,$action]) }}" style="display:inline-flex;gap:8px;margin-top:10px">@csrf<input type="hidden" name="project_version" value="{{ $project->plan_version }}"><input type="hidden" name="command" value="{{ $command }}">@if(in_array($command,['reject','reopen']))<input name="reason" placeholder="理由" required>@endif<button class="s8-button">{{ $label }}</button></form>@endforeach
@if($project->owner_user_id === auth()->id() || $action->assigned_to === auth()->id())
<details style="margin-top:12px"><summary>Edit plan</summary><form class="s8-form" method="POST" action="{{ route('project-execution.actions.update', [$project,$action]) }}">@csrf @method('PUT')<input type="hidden" name="project_version" value="{{ $project->plan_version }}"><input name="title" value="{{ $action->title }}" required><textarea name="description">{{ $action->description }}</textarea><textarea name="done_condition" required>{{ $action->done_condition }}</textarea><input type="date" name="due_date" value="{{ $action->due_date?->format('Y-m-d') }}"><input name="reason" placeholder="Reason required when due date changes"><button class="s8-button">Update Action</button></form></details>
@endif
@if($project->owner_user_id === auth()->id())
<details style="margin-top:12px"><summary>Move or archive</summary><form class="s8-form" method="POST" action="{{ route('project-execution.actions.move', [$project,$action]) }}">@csrf<input type="hidden" name="project_version" value="{{ $project->plan_version }}"><select name="improvement_id"><option value="">Project direct</option>@foreach($project->roadmaps as $roadmap)@foreach($roadmap->improvements as $theme)<option value="{{ $theme->id }}" @selected($action->improvement_id===$theme->id)>{{ $roadmap->title }} / {{ $theme->title }}</option>@endforeach @endforeach</select><input type="number" min="1" name="sort_order" value="{{ $action->sort_order }}" required><button class="s8-button">Move Action</button></form><form class="s8-form" method="POST" action="{{ route('project-execution.archive', $project) }}">@csrf<input type="hidden" name="project_version" value="{{ $project->plan_version }}"><input type="hidden" name="type" value="action"><input type="hidden" name="entity_id" value="{{ $action->id }}"><input name="reason" required placeholder="Archive reason"><button class="s8-button">Archive Action</button></form></details>
@endif
</article>
