<template data-theme-template><fieldset class="amp-field-item" data-theme><legend>New Theme</legend><div class="field"><label>Theme Statement</label><textarea name="themes[__T__][statement]" maxlength="50000"></textarea></div><div class="field"><label>説明（任意）</label><textarea name="themes[__T__][explanation]" maxlength="50000"></textarea></div><div class="amp-field-list" data-priorities></div><div class="actions"><button class="secondary" type="button" data-add-priority>Priorityを追加</button><button class="danger-outline" type="button" data-remove>Themeを削除</button></div></fieldset></template>
<template data-priority-template><div class="amp-field-item" data-priority><div class="field"><label>Priority</label><textarea name="themes[__T__][priorities][__P__][statement]" maxlength="50000"></textarea></div><div class="field"><label>説明（任意）</label><textarea name="themes[__T__][priorities][__P__][explanation]" maxlength="50000"></textarea></div><button class="danger-outline" type="button" data-remove>削除</button></div></template>
<template data-department-template><fieldset class="amp-field-item" data-department><legend>New Department</legend><div class="field"><label>Organization Group</label><select name="departments[__D__][group_public_id]" required><option value="">選択してください</option>@foreach($groups as $group)<option value="{{ $group->public_id }}">{{ $group->name }}</option>@endforeach</select></div><div class="field"><label>部署の説明（任意）</label><textarea name="departments[__D__][introduction]" maxlength="50000"></textarea></div><div class="amp-field-list" data-statements></div><div class="actions"><button class="secondary" type="button" data-add-statement>方針を追加</button><button class="danger-outline" type="button" data-remove>部署を削除</button></div></fieldset></template>
<template data-statement-template><div class="amp-field-item" data-statement><div class="field"><label>Department Policy</label><textarea name="departments[__D__][statements][__S__][statement]" maxlength="50000"></textarea></div><div class="field"><label>説明（任意）</label><textarea name="departments[__D__][statements][__S__][explanation]" maxlength="50000"></textarea></div><button class="danger-outline" type="button" data-remove>削除</button></div></template>
<script>
(() => {
 const form=document.querySelector('[data-amp-form]'); if(!form)return;
 let theme={{ $themeStart }},department={{ $departmentStart }};
 const html=name=>document.querySelector(`[data-${name}-template]`).innerHTML;
 form.querySelector('[data-add-theme]').addEventListener('click',()=>{const i=theme++;form.querySelector('[data-themes]').insertAdjacentHTML('beforeend',html('theme').replaceAll('__T__',String(i)));});
 form.querySelector('[data-add-department]').addEventListener('click',()=>{const i=department++;form.querySelector('[data-departments]').insertAdjacentHTML('beforeend',html('department').replaceAll('__D__',String(i)));});
 form.addEventListener('click',event=>{
  const remove=event.target.closest('[data-remove]'); if(remove){remove.closest('[data-theme],[data-priority],[data-department],[data-statement]').remove();return;}
  const priority=event.target.closest('[data-add-priority]'); if(priority){const owner=priority.closest('[data-theme]');const match=owner.querySelector('[name^="themes["]').name.match(/themes\[(\d+)\]/);const list=owner.querySelector('[data-priorities]');const i=list.children.length;list.insertAdjacentHTML('beforeend',html('priority').replaceAll('__T__',match[1]).replaceAll('__P__',String(i)));return;}
  const statement=event.target.closest('[data-add-statement]'); if(statement){const owner=statement.closest('[data-department]');const match=owner.querySelector('[name^="departments["]').name.match(/departments\[(\d+)\]/);const list=owner.querySelector('[data-statements]');const i=list.children.length;list.insertAdjacentHTML('beforeend',html('statement').replaceAll('__D__',match[1]).replaceAll('__S__',String(i)));}
 });
})();
</script>
