@extends('layouts.app', ['title' => '年度経営方針を編集 - '.$organization->name])

@section('content')
@include('annual-management-policy._styles')
@php
    $themes = old('themes', $annualPolicy->themes->map(fn($theme) => ['public_id'=>$theme->public_id,'statement'=>$theme->statement,'explanation'=>$theme->explanation,'priorities'=>$theme->priorities->map(fn($priority)=>['public_id'=>$priority->public_id,'statement'=>$priority->statement,'explanation'=>$priority->explanation])->all()])->all());
    $departments = old('departments', $annualPolicy->departments->map(fn($department) => ['public_id'=>$department->public_id,'group_public_id'=>$department->group->public_id,'introduction'=>$department->introduction,'statements'=>$department->statements->map(fn($statement)=>['public_id'=>$statement->public_id,'statement'=>$statement->statement,'explanation'=>$statement->explanation])->all()])->all());
@endphp
<section class="amp-shell">
    <header class="amp-header"><div><p class="amp-kicker">DRAFT / NOT APPROVED</p><h1>{{ $annualPolicy->period->display_label }} の方針を作成</h1><p>保存だけでは正式版になりません。承認画面で全体を確認してから正式化します。</p></div><a class="button secondary" href="{{ route('annual-management-policy.show', $annualPolicy) }}">読む画面へ戻る</a></header>
    @if($errors->any())<div class="panel" role="alert"><strong>保存できませんでした。</strong>@foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach</div>@endif
    <form method="POST" action="{{ route('annual-management-policy.update', $annualPolicy) }}" class="amp-form" data-amp-form>@csrf @method('PUT')
        <input type="hidden" name="request_id" value="{{ old('request_id', $requestId) }}"><input type="hidden" name="expected_draft_version" value="{{ $annualPolicy->draft_version }}">
        <fieldset><legend>対象期間</legend><div class="field"><label for="period-name">方針に表示する年度・期間名</label><input id="period-name" name="period_name" maxlength="120" value="{{ old('period_name', $annualPolicy->draft_period_name ?? $annualPolicy->period->name) }}"></div><div class="amp-row"><div class="field"><label for="starts-on">開始日</label><input id="starts-on" type="date" name="starts_on" value="{{ old('starts_on', $annualPolicy->draft_starts_on?->toDateString() ?? $annualPolicy->period->starts_on->toDateString()) }}"></div><div class="field"><label for="ends-on">終了日</label><input id="ends-on" type="date" name="ends_on" value="{{ old('ends_on', $annualPolicy->draft_ends_on?->toDateString() ?? $annualPolicy->period->ends_on->toDateString()) }}"></div></div><small>承認時に固定される表示用snapshotです。会社共通の期数や、現在有効かどうかの判定は変更しません。</small></fieldset>
        <fieldset><legend>全社方針</legend><div class="field"><label for="purpose">今期、何を実現したいのか（任意）</label><small>この年度に到達したい状態を、短く具体的に記します。</small><textarea id="purpose" name="purpose" maxlength="50000" placeholder="例：全社で判断軸を共有し、強みを再現できる組織へ進む。">{{ old('purpose', $annualPolicy->draft_purpose) }}</textarea></div><div class="field"><label for="background">この方針を定める背景（任意）</label><small>現在の状況、課題、機会を記します。</small><textarea id="background" name="background" maxlength="50000" placeholder="例：事業拡大に伴い、個人の経験を会社の仕組みに変える必要がある。">{{ old('background', $annualPolicy->draft_background) }}</textarea></div><div class="field"><label for="policy">年度経営方針（承認時は必須）</label><small>今期の判断と行動の中心になる方針です。</small><textarea id="policy" name="policy" maxlength="50000" placeholder="例：強みを仕組みに変え、全員が同じ方向を向いて動ける会社をつくる。">{{ old('policy', $annualPolicy->draft_policy) }}</textarea></div></fieldset>
        <section class="stack"><div class="amp-section-heading"><div><p class="amp-kicker">FOCUS THEMES</p><h2>重点テーマと優先方針</h2><p>重点テーマの中に、複数の優先方針を整理できます。</p></div><button class="secondary" type="button" data-add-theme>重点テーマを追加</button></div><div class="amp-field-list" data-themes>
            @foreach($themes as $ti=>$theme)<fieldset class="amp-field-item" data-theme><legend>重点テーマ {{ $loop->iteration }}</legend><div class="amp-order-actions"><button class="secondary" type="button" data-move-up aria-label="重点テーマを上へ">↑</button><button class="secondary" type="button" data-move-down aria-label="重点テーマを下へ">↓</button></div>@if(filled($theme['public_id']??null))<input type="hidden" name="themes[{{ $ti }}][public_id]" value="{{ $theme['public_id'] }}">@endif<div class="field"><label>重点テーマ名</label><textarea name="themes[{{ $ti }}][statement]" maxlength="50000">{{ $theme['statement']??'' }}</textarea></div><div class="field"><label>背景・考え方（任意）</label><textarea name="themes[{{ $ti }}][explanation]" maxlength="50000">{{ $theme['explanation']??'' }}</textarea></div><div class="amp-field-list" data-priorities>@foreach($theme['priorities']??[] as $pi=>$priority)<div class="amp-field-item amp-field-item--nested" data-priority><div class="amp-item-title">優先方針 {{ $loop->iteration }}</div><div class="amp-order-actions"><button class="secondary" type="button" data-move-up aria-label="優先方針を上へ">↑</button><button class="secondary" type="button" data-move-down aria-label="優先方針を下へ">↓</button></div>@if(filled($priority['public_id']??null))<input type="hidden" name="themes[{{ $ti }}][priorities][{{ $pi }}][public_id]" value="{{ $priority['public_id'] }}">@endif<div class="field"><label>優先方針</label><textarea name="themes[{{ $ti }}][priorities][{{ $pi }}][statement]">{{ $priority['statement']??'' }}</textarea></div><div class="field"><label>方針の考え方（任意）</label><textarea name="themes[{{ $ti }}][priorities][{{ $pi }}][explanation]">{{ $priority['explanation']??'' }}</textarea></div><button class="danger-outline" type="button" data-remove>削除</button></div>@endforeach</div><div class="actions"><button class="secondary" type="button" data-add-priority>優先方針を追加</button><button class="danger-outline" type="button" data-remove>重点テーマを削除</button></div></fieldset>@endforeach
        </div></section>
        <section class="stack"><div class="amp-section-heading"><div><p class="amp-kicker">DEPARTMENT POLICIES</p><h2>部署方針</h2><p>Organizationに登録済みの部署・グループを対象にします。</p></div>@if($groups->isNotEmpty())<button class="secondary" type="button" data-add-department>部署方針を追加</button>@endif</div>
        @if($groups->isEmpty())<div class="amp-empty amp-empty--action"><strong>部署がまだ登録されていません</strong><p>部署方針を作成するには、先に部署・グループを登録してください。現在の入力内容は先にDraftとして保存します。</p><button type="submit" name="after_save" value="organization_groups">Draftを保存して部署・グループを設定する</button></div>@endif
        <div class="amp-field-list" data-departments>
            @foreach($departments as $di=>$department)<fieldset class="amp-field-item" data-department><legend>部署方針 {{ $loop->iteration }}</legend><div class="amp-order-actions"><button class="secondary" type="button" data-move-up aria-label="部署方針を上へ">↑</button><button class="secondary" type="button" data-move-down aria-label="部署方針を下へ">↓</button></div>@if(filled($department['public_id']??null))<input type="hidden" name="departments[{{ $di }}][public_id]" value="{{ $department['public_id'] }}">@endif<div class="field"><label>対象部署</label><select name="departments[{{ $di }}][group_public_id]" required><option value="">部署を選択してください</option>@foreach($groups as $group)<option value="{{ $group->public_id }}" @selected(($department['group_public_id']??null)===$group->public_id)>{{ $group->name }}</option>@endforeach</select></div><div class="field"><label>部署方針全体の背景・考え方（任意）</label><textarea name="departments[{{ $di }}][introduction]">{{ $department['introduction']??'' }}</textarea></div><div class="amp-field-list" data-statements>@foreach($department['statements']??[] as $si=>$statement)<div class="amp-field-item amp-field-item--nested" data-statement><div class="amp-item-title">部署方針 {{ $loop->iteration }}</div><div class="amp-order-actions"><button class="secondary" type="button" data-move-up aria-label="部署方針項目を上へ">↑</button><button class="secondary" type="button" data-move-down aria-label="部署方針項目を下へ">↓</button></div>@if(filled($statement['public_id']??null))<input type="hidden" name="departments[{{ $di }}][statements][{{ $si }}][public_id]" value="{{ $statement['public_id'] }}">@endif<div class="field"><label>部署方針</label><textarea name="departments[{{ $di }}][statements][{{ $si }}][statement]">{{ $statement['statement']??'' }}</textarea></div><div class="field"><label>方針の背景・考え方（任意）</label><textarea name="departments[{{ $di }}][statements][{{ $si }}][explanation]">{{ $statement['explanation']??'' }}</textarea></div><button class="danger-outline" type="button" data-remove>削除</button></div>@endforeach</div><div class="actions"><button class="secondary" type="button" data-add-statement>部署方針を追加</button><button class="danger-outline" type="button" data-remove>対象部署を削除</button></div></fieldset>@endforeach
        </div></section>
        <div class="actions amp-form-actions"><button type="submit">Draftを保存</button><a class="button secondary" href="{{ route('annual-management-policy.show', $annualPolicy) }}">キャンセル</a></div>
    </form>
</section>
@include('annual-management-policy._form-script', ['groups'=>$groups])
@endsection
