@extends('layouts.app', ['title' => '年度経営方針を編集 - '.$organization->name])

@section('content')
@include('annual-management-policy._styles')
@php
    $themes = old('themes', $annualPolicy->themes->map(fn($theme) => ['public_id'=>$theme->public_id,'statement'=>$theme->statement,'explanation'=>$theme->explanation,'priorities'=>$theme->priorities->map(fn($priority)=>['public_id'=>$priority->public_id,'statement'=>$priority->statement,'explanation'=>$priority->explanation])->all()])->all());
    $departments = old('departments', $annualPolicy->departments->map(fn($department) => ['public_id'=>$department->public_id,'group_public_id'=>$department->group->public_id,'introduction'=>$department->introduction,'statements'=>$department->statements->map(fn($statement)=>['public_id'=>$statement->public_id,'statement'=>$statement->statement,'explanation'=>$statement->explanation])->all()])->all());
@endphp
<section class="amp-shell">
    <header class="amp-header"><div><p class="amp-kicker">DRAFT / NOT APPROVED</p><h1>{{ $annualPolicy->period->name }} の方針を作成</h1><p>ここで保存しても正式版にはなりません。承認画面で全体を確認してから正式化します。</p></div><a class="button secondary" href="{{ route('annual-management-policy.show', $annualPolicy) }}">読む画面へ戻る</a></header>
    @if($errors->any())<div class="panel" role="alert"><strong>保存できませんでした。</strong>@foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach</div>@endif
    <form method="POST" action="{{ route('annual-management-policy.update', $annualPolicy) }}" class="amp-form" data-amp-form>@csrf @method('PUT')
        <input type="hidden" name="request_id" value="{{ old('request_id', $requestId) }}"><input type="hidden" name="expected_draft_version" value="{{ $annualPolicy->draft_version }}">
        <fieldset><legend>対象期間</legend><div class="field"><label for="period-name">方針に表示する期間名</label><input id="period-name" name="period_name" maxlength="120" value="{{ old('period_name', $annualPolicy->draft_period_name ?? $annualPolicy->period->name) }}"></div><div class="amp-row"><div class="field"><label for="starts-on">開始日</label><input id="starts-on" type="date" name="starts_on" value="{{ old('starts_on', $annualPolicy->draft_starts_on?->toDateString() ?? $annualPolicy->period->starts_on->toDateString()) }}"></div><div class="field"><label for="ends-on">終了日</label><input id="ends-on" type="date" name="ends_on" value="{{ old('ends_on', $annualPolicy->draft_ends_on?->toDateString() ?? $annualPolicy->period->ends_on->toDateString()) }}"></div></div><small>会社の期間とは別の表示用snapshotです。変更しても「今期」の判定は変わりません。</small></fieldset>
        <fieldset><legend>全社方針</legend><div class="field"><label for="purpose">Purpose（任意）</label><textarea id="purpose" name="purpose" maxlength="50000">{{ old('purpose', $annualPolicy->draft_purpose) }}</textarea></div><div class="field"><label for="background">Background（任意）</label><textarea id="background" name="background" maxlength="50000">{{ old('background', $annualPolicy->draft_background) }}</textarea></div><div class="field"><label for="policy">Policy（正式承認時は必須）</label><textarea id="policy" name="policy" maxlength="50000">{{ old('policy', $annualPolicy->draft_policy) }}</textarea></div></fieldset>
        <section class="stack"><div class="actions" style="justify-content:space-between"><div><p class="amp-kicker">THEMES / 0..N</p><h2>重点テーマと優先方針</h2></div><button class="secondary" type="button" data-add-theme>Themeを追加</button></div><div class="amp-field-list" data-themes>
            @foreach($themes as $ti=>$theme)<fieldset class="amp-field-item" data-theme><legend>Theme {{ $loop->iteration }}</legend>@if(filled($theme['public_id']??null))<input type="hidden" name="themes[{{ $ti }}][public_id]" value="{{ $theme['public_id'] }}">@endif<div class="field"><label>Theme Statement</label><textarea name="themes[{{ $ti }}][statement]" maxlength="50000">{{ $theme['statement']??'' }}</textarea></div><div class="field"><label>説明（任意）</label><textarea name="themes[{{ $ti }}][explanation]" maxlength="50000">{{ $theme['explanation']??'' }}</textarea></div><div class="amp-field-list" data-priorities>@foreach($theme['priorities']??[] as $pi=>$priority)<div class="amp-field-item" data-priority>@if(filled($priority['public_id']??null))<input type="hidden" name="themes[{{ $ti }}][priorities][{{ $pi }}][public_id]" value="{{ $priority['public_id'] }}">@endif<div class="field"><label>Priority</label><textarea name="themes[{{ $ti }}][priorities][{{ $pi }}][statement]">{{ $priority['statement']??'' }}</textarea></div><div class="field"><label>説明（任意）</label><textarea name="themes[{{ $ti }}][priorities][{{ $pi }}][explanation]">{{ $priority['explanation']??'' }}</textarea></div><button class="danger-outline" type="button" data-remove>削除</button></div>@endforeach</div><div class="actions"><button class="secondary" type="button" data-add-priority>Priorityを追加</button><button class="danger-outline" type="button" data-remove>Themeを削除</button></div></fieldset>@endforeach
        </div></section>
        <section class="stack"><div class="actions" style="justify-content:space-between"><div><p class="amp-kicker">DEPARTMENTS / 0..N</p><h2>部署方針</h2></div><button class="secondary" type="button" data-add-department>部署を追加</button></div><div class="amp-field-list" data-departments>
            @foreach($departments as $di=>$department)<fieldset class="amp-field-item" data-department><legend>部署 {{ $loop->iteration }}</legend>@if(filled($department['public_id']??null))<input type="hidden" name="departments[{{ $di }}][public_id]" value="{{ $department['public_id'] }}">@endif<div class="field"><label>Organization Group</label><select name="departments[{{ $di }}][group_public_id]" required><option value="">選択してください</option>@foreach($groups as $group)<option value="{{ $group->public_id }}" @selected(($department['group_public_id']??null)===$group->public_id)>{{ $group->name }}</option>@endforeach</select></div><div class="field"><label>部署の説明（任意）</label><textarea name="departments[{{ $di }}][introduction]">{{ $department['introduction']??'' }}</textarea></div><div class="amp-field-list" data-statements>@foreach($department['statements']??[] as $si=>$statement)<div class="amp-field-item" data-statement>@if(filled($statement['public_id']??null))<input type="hidden" name="departments[{{ $di }}][statements][{{ $si }}][public_id]" value="{{ $statement['public_id'] }}">@endif<div class="field"><label>Department Policy</label><textarea name="departments[{{ $di }}][statements][{{ $si }}][statement]">{{ $statement['statement']??'' }}</textarea></div><div class="field"><label>説明（任意）</label><textarea name="departments[{{ $di }}][statements][{{ $si }}][explanation]">{{ $statement['explanation']??'' }}</textarea></div><button class="danger-outline" type="button" data-remove>削除</button></div>@endforeach</div><div class="actions"><button class="secondary" type="button" data-add-statement>方針を追加</button><button class="danger-outline" type="button" data-remove>部署を削除</button></div></fieldset>@endforeach
        </div></section>
        <div class="actions"><button type="submit">Draftを保存</button><a class="button secondary" href="{{ route('annual-management-policy.show', $annualPolicy) }}">キャンセル</a></div>
    </form>
</section>
@include('annual-management-policy._form-script', ['groups'=>$groups, 'themeStart'=>count($themes), 'departmentStart'=>count($departments)])
@endsection
