@extends('layouts.app', ['title' => '年度経営方針の関連付け - '.$organization->name])
@section('content')
@include('annual-management-policy._styles')
<section class="amp-shell"><header class="amp-header"><div><p class="amp-kicker">MANUAL SEMANTIC RELATIONS</p><h1>関連付け</h1><p>方針とProject / Action等を、人が確認して関連付けます。実行情報を方針へ複製しません。</p></div><a class="button secondary" href="{{ route('annual-management-policy.show',$annualPolicy) }}">方針へ戻る</a></header>
 @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="panel" role="alert">@foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach</div>@endif
 <form method="POST" action="{{ route('annual-management-policy.relations.store',$annualPolicy) }}" class="amp-form panel">@csrf<input type="hidden" name="request_id" value="{{ $requestId }}"><input type="hidden" name="expected_relation_version" value="{{ $annualPolicy->relation_version }}"><h2>関連を追加</h2>
  <div class="amp-row"><div class="field"><label>関連元の種類</label><select name="source_type" required><option value="annual">Annual全体</option><option value="theme">Theme</option><option value="priority">Priority</option><option value="department">Department</option></select></div><div class="field"><label>関連元</label><select name="source_public_id" required><option value="{{ $annualPolicy->public_id }}">Annual全体</option>@foreach($annualPolicy->themes as $theme)<option value="{{ $theme->public_id }}">Theme: {{ \Illuminate\Support\Str::limit($theme->statement,50) }}</option>@foreach($theme->priorities as $priority)<option value="{{ $priority->public_id }}">Priority: {{ \Illuminate\Support\Str::limit($priority->statement,50) }}</option>@endforeach @endforeach @foreach($annualPolicy->departments as $department)<option value="{{ $department->public_id }}">Department: {{ $department->group->name }}</option>@endforeach</select></div></div>
  <div class="amp-row"><div class="field"><label>関連先の種類</label><select name="target_type" required><option value="project">Project</option><option value="action">Action</option><option value="group">Group（Priorityのみ）</option><option value="department">Department（Priorityのみ）</option></select></div><div class="field"><label>関連先</label><select name="target_public_id" required>@foreach($projects as $project)<option value="{{ $project->public_id }}">Project: {{ $project->name }}</option>@endforeach @foreach($actions as $action)<option value="{{ $action->public_id }}">Action: {{ $action->title }}</option>@endforeach @foreach($groups as $group)<option value="{{ $group->public_id }}">Group: {{ $group->name }}</option>@endforeach @foreach($annualPolicy->departments as $department)<option value="{{ $department->public_id }}">Department: {{ $department->group->name }}</option>@endforeach</select></div></div>
  <div class="field"><label>関連付け理由（任意）</label><textarea name="reason" maxlength="2000"></textarea></div><div><button type="submit">確認済みの関連として追加</button></div>
 </form>
 <div class="stack"><h2>Relation Version {{ $annualPolicy->relation_version }}</h2>@forelse($annualPolicy->relations as $relation)<article class="amp-section"><div class="actions" style="justify-content:space-between"><div><strong>{{ $relation->source_type }} → {{ $relation->target_type }}</strong><div class="meta">{{ $relation->current_status }} / version {{ $relation->current_version }}</div></div>@if($relation->current_status==='confirmed')<form method="POST" action="{{ route('annual-management-policy.relations.withdraw',[$annualPolicy,$relation]) }}">@csrf<input type="hidden" name="request_id" value="{{ \Illuminate\Support\Str::uuid() }}"><input type="hidden" name="expected_relation_version" value="{{ $annualPolicy->relation_version }}"><button class="danger-outline" type="submit">関連を撤回</button></form>@endif</div></article>@empty<div class="amp-empty">関連付けはありません。</div>@endforelse</div>
</section>
@endsection
